version: '3.4'
services:
  db:
    image: mdillon/postgis:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - '.docker/db:/var/lib/db/data'
volumes:
  db: {}
