version: '3.4'
services:
  db:
    image: postgis/postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - '.docker/db:/var/lib/postgresql'
volumes:
  db: {}
